var TASKS = {
  COVER_IT: 'coverIt',
  HIT_BTN: 'hitButton',
  //EXHALE: 'exhale',
  TWIST_CLOCKWISE: 'twistClockwise',
  TWIST_COUNTER_CLOCKWISE: 'twistCounterClockwise',
  TWIST_IT: 'twistIt'
};

var GAME_OVER_TYPES = {
  TIMEOUT: 'timeout',
  WRONG_TASK: 'wrongTask'
};

var BUZZ = {
  SHORT: 'short',
  LONG: 'long'
};

var GYROS_THRESHOLD = 100;

var POT_THRESHOLD = 5;

var HUMIDITY_THRESHOLD = 70;

var MAX_GYROS_STATES = 10;

module.exports = {
  TASKS: TASKS,
  GAME_OVER_TYPES: GAME_OVER_TYPES,
  GYROS_THRESHOLD: GYROS_THRESHOLD,
  POT_THRESHOLD: POT_THRESHOLD,
  HUMIDITY_THRESHOLD: HUMIDITY_THRESHOLD,
  BUZZ: BUZZ,
  MAX_GYROS_STATES: MAX_GYROS_STATES
};
